version: "3.6"

services:
  vue-admin:
    image: node:10-slim
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./node/vue-element-admin:/home/node/app
    ports:
      - 9501-9550:9527
    command: "npm run dev"

  flask-profiler:
    build: ./python/flask-profiler
    ports:
      - 5001-5050:5000
